#!/bin/bash

set -eu
shopt -s nullglob

delete() {
    btrfs property set -ts "$1" ro false
    btrfs subvolume delete "$1"
}

backup_to_date() {
    date -u -d "$(basename "$1")" '+%s'
}

identity="$(id -u)-$(id -g)"
check_owner() {
    local id mode
    read -r id mode < <(stat -c "%u-%g %#a")
    [[ "$id" == "$identity" ]] && [[ $(( "$mode" & !0755 )) -eq 0 ]]
}

err() {
    local ret=$?
    if [[ $ret -eq 0 ]]; then
        ret=1
    fi
    echo "$@" >&2
    return $ret
}

backup_dir="./.backups"
lock_file="${backup_dir}/.lock"
now="$(date -u '+%s')"
day_length=$(( 60 * 60 * 24 ))
month_length=$(( day_length * 30 ))
week_length=$(( day_length * 7 ))
year_length=$(( day_length * 365 ))

cd "$1" || err "Failed to change directory into the subvolume: $1"
check_owner "." || err "Refusing to snapshot a directory we don't own."

[[ -d "${backup_dir}" ]] || exit 0 # Nothing to do
check_owner "${backup_dir}" || err "Refusing use a backup dir we don't own."

exec 4<> "${lock_file}"
flock -n 4 || err "Failed to take lock."

last_backup_date=0

while read -r fname; do
    backup_date="$(backup_to_date "${fname}")"

    time_since_last_backup="$(( backup_date - last_backup_date ))"
    time_until_now="$(( now - backup_date ))"

    if [[ ${time_until_now} -gt ${year_length} ]]; then
        if [[ ${time_since_last_backup} -gt ${month_length} ]]; then
            last_backup_date=$(( backup_date - ( backup_date % month_length ) ))
        else
            delete "$fname"
        fi
    elif [[ ${time_until_now} -gt ${month_length} ]]; then
        if [[ ${time_since_last_backup} -gt ${week_length} ]]; then
            last_backup_date=$(( backup_date - ( backup_date % week_length ) ))
        else
            delete "$fname"
        fi
    elif [[ ${time_until_now} -gt ${day_length} ]]; then
        if [[ ${time_since_last_backup} -gt ${day_length} ]]; then
            last_backup_date=$(( backup_date - ( backup_date % day_length ) ))
        else
            delete "$fname"
        fi
    else
        # All done!
        break
    fi
done < <( find "${backup_dir}" -mindepth 1 -maxdepth 1 -type d -name '[!.]*' | sort )

btrfs filesystem sync "${backup_dir}"
