#!/bin/bash
set -e

subvol="$1"
backup_dir="${subvol}/.backups"
ignore_file="${backup_dir}/ignore"
backup_dir="${2:-${subvol}/.backups}"
today_dir="${backup_dir}/$(date -u +%FT%T)"
current_dir="${backup_dir}/current"

err() {
    local ret=$?
    if [[ $ret -eq 0 ]]; then
        ret=1
    fi
    echo "$@" >&2
    return $ret
}

cd /
test -d "${subvol}" || err "No such directory: ${subvol}"
mkdir -p "${backup_dir}"
chmod 0700 "${backup_dir}"

btrfs subvolume snapshot "${subvol}" "${today_dir}"

if [[ -e "${ignore_file}" ]]; then
    while read -r fname; do
        target="${today_dir:?}/${fname}"
        [[ -e "${target}" ]] || continue
        rm -rf -- "${target}"
    done < "${ignore_file}"
fi

# Clean ignored files (build artifacts, etc.).
find "${today_dir:?}" -mount -depth -type d -name .git -execdir git clean -Xqfd \;

# Remove all cache directories, but don't descend into .git directories.
find "${today_dir:?}" -mount -depth -type f -name CACHEDIR.TAG -printf '%h\0' \
    | xargs -r -0 rm --one-file-system -rf --

btrfs property set -ts "$today_dir" ro true

ln -T -rsf "${today_dir}" "${current_dir}"

